/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistratiRouteImport } from './routes/registrati'
import { Route as IndexRouteImport } from './routes/index'

const RegistratiRoute = RegistratiRouteImport.update({
  id: '/registrati',
  path: '/registrati',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registrati': typeof RegistratiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registrati': typeof RegistratiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registrati': typeof RegistratiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/registrati'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/registrati'
  id: '__root__' | '/' | '/registrati'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistratiRoute: typeof RegistratiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrati': {
      id: '/registrati'
      path: '/registrati'
      fullPath: '/registrati'
      preLoaderRoute: typeof RegistratiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistratiRoute: RegistratiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
